contact_links:
  - name: ğŸ™Œ Contribution Guide
    url: https://github.com/antfu/contribute
    about: Please read through before making contributions.
  - name: ğŸ’¬ Anthony's Discord Server
    url: https://chat.antfu.me/
    about: Want to discuss / chat with the community? Here you go!
  - name: â‰ï¸ Why and How to make a reproduction?
    url: https://antfu.me/posts/why-reproductions-are-required
    about: Reproduction is very important for maintainer to help on your issues!
